name: Publish Notion website to GitHub Pages

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout loconotion
        uses: actions/checkout@v3
        with:
          repository: leoncvlt/loconotion
          path: loconotion
          ref: "tags/0.1.3"  # 修正版本引用格式

      - name: Checkout this repo
        uses: actions/checkout@v3
        with:
          path: pages_repo

      - name: Setup ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium chromium-chromedriver
          sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/local/bin

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install urllib3==1.26.18
          pip install six==1.16.0
          pip install -r loconotion/requirements.txt

      - name: Run Loconotion
        run: |
          python -m loconotion --chromedriver /usr/local/bin/chromedriver --headless "pages_repo/site.toml"

      - name: Push to GitHub pages
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          GIT_DEPLOY_DIR=../dist/site \
          GIT_DEPLOY_BRANCH=gh-pages \
          GIT_DEPLOY_REPO="https://${{ github.token }}@github.com/${{ github.repository }}.git" ./deploy.sh
        working-directory: pages_repo
